apiVersion: v1
kind: ConfigMap
metadata:
  name: ${project.artifactId}
  namespace: deepsea
data:
  deepsea.ui.http.address: 0.0.0.0
  deepsea.ui.http.port: 8080
  keycloak.realm: master
  keycloak.auth-server-url: http://keycloak-deepsea.192.168.99.100.nip.io/auth
  keycloak.ssl-required: external
  keycloak.resource: deepsea
  keycloak.credentials.secret: 769a8bff-cfbd-471f-bb9c-fc5db2f29c0c
  keycloak.use-resource-role-mappings: true
  keycloak.confidential-port: 0
