pipeline:
  name: deepsea-test
  identifier: deepseatest
  projectIdentifier: test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: testing
        identifier: testing
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo Testing
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
