apiVersion: v1
kind: ConfigMap
metadata:
  name: ${project.artifactId}
  namespace: deepsea
data:
  database.name: sampledb
  enrolment.http.address: 0.0.0.0
  enrolment.http.port: 8080
  enrolment.service: deepsea-admin-enrolment.deepsea.svc
