---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: deepsea-underwriting-ui
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: deepsea-underwriting-ui@sha256:81104c5b651792907738ec3488e0559bd8d1f88d07a3ce74964bfc9f09f70a66
        namespace: deepsea
      name: latest
