apiVersion: v1
kind: ConfigMap
metadata:
  name: ${project.artifactId}
  namespace: deepsea
data:
  database.name: sampledb
  mta.http.address: 0.0.0.0
  mta.http.port: 8080
  mta.service: deepsea-admin-mta.deepsea.svc
  