---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: deepsea-ui
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: deepsea-ui@sha256:383fbac9626a4da91c0eb71af06aae2365e86bee3d17198f6f3f3ab328ac31f5
        namespace: deepsea
      name: latest
