---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: deepsea-underwriting-ui
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: deepsea-underwriting-ui@sha256:171c59b8127a32650fc6209747b32d49d132029ac7818a0927dce5b255475315
        namespace: deepsea
      name: latest
