---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: deepsea-underwriting-actuarial
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: deepsea-underwriting-actuarial@sha256:f454d036df4ab43947822497ff622697a754ccbbc5f626c4d2fc737a975aea28
        namespace: deepsea
      name: latest
