apiVersion: v1
kind: ConfigMap
metadata:
  name: ${project.artifactId}
  namespace: deepsea
data:
  mongo.username: userND8
  mongo.password: kte876p60f6Y4LsM
  mongo.host: mongodb
  mongo.port: 27017
  mongo.database: sampledb
  mysql.database: sampledb
  client.host.address: 0.0.0.0
  client.host.port: 8080
  client.service.hostname: deepsea-client.deepsea.svc
  client.api.name: client
  