apiVersion: v1
kind: ConfigMap
metadata:
  name: ${project.artifactId}
  namespace: deepsea
data:
  database.host: mongodb
  database.port: 27017
  redis.host: redis
  redis.port: 6379
  menu.host.address: 0.0.0.0
  menu.host.port: 8080
  menu.service.hostname: deepsea-ui-menu.deepsea.svc
  
  